# Generated by Django 5.1.2 on 2024-10-12 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='play',
        ),
        migrations.AddField(
            model_name='play',
            name='genre',
            field=models.ManyToManyField(related_name='genres', to='api.genre'),
        ),
    ]
