# Generated by Django 5.1.2 on 2024-10-12 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_genre_play_genres'),
    ]

    operations = [
        migrations.RenameField(
            model_name='performance',
            old_name='TheatreHall',
            new_name='theatre_hall',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='play',
        ),
        migrations.AddField(
            model_name='play',
            name='actors',
            field=models.ManyToManyField(related_name='actors', to='api.actor'),
        ),
    ]
