# Generated by Django 5.1.2 on 2024-10-15 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_actor_options_alter_genre_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="performance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets",
                to="api.performance",
            ),
        ),
    ]
