# Generated by Django 5.1.2 on 2024-10-13 14:22

import theatre.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0005_alter_ticket_reservation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={'ordering': ('last_name', 'first_name')},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='performance',
            options={'ordering': ('play',)},
        ),
        migrations.AlterModelOptions(
            name='play',
            options={'ordering': ('title',)},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='theatrehall',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='play',
            name='image',
            field=models.ImageField(null=True, upload_to=theatre.models.play_image_file_path),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('row', 'seat', 'performance'), name='unique_ticket'),
        ),
    ]
