# Generated by Django 5.1.2 on 2024-10-30 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theatre", "0007_alter_ticket_performance"),
    ]

    operations = [
        migrations.AddField(
            model_name="play",
            name="wikipedia_article",
            field=models.TextField(blank=True, null=True),
        ),
    ]
